### ISSUE TITLE
Pequeno bug ao exibir playlist com nome muito grande

### ISSUE THREAD

**Issue by brunodesde1987** [luizbaldi/playlist-converter#1]
Opa! Parabéns Baldi pela ferramenta! 👏 
Estou brincando por aqui e deixo essa pequena sugestão. 😉 

### Problema
O problema ocorre quando o nome da playlist é maior do que a largura do `Select`:
![image](https://user-images.githubusercontent.com/28319535/78156857-b9e2b880-7415-11ea-81ac-766747f3d57d.png)

Pelo que entendi isso é um problema da lib [react95](https://arturbien.github.io/React95/?path=/story/select--fixed-width):
![image](https://user-images.githubusercontent.com/28319535/78158708-f7484580-7417-11ea-8c2d-44f3f92942c4.png)

### Sugestão
Editar o `StyledSelect` para evitar que isso aconteça:
```jsx
const StyledSelect = styled(Select)`
  width: 80%;

  ul li {
    text-overflow: ellipsis;
    overflow: hidden;
  }
`;
```

Eles já utilizam o `white-space: nowrap;` no `li` então com essa combinação o resultado fica assim:
![image](https://user-images.githubusercontent.com/28319535/78158596-d54ec300-7417-11ea-9d6b-f34db0d06305.png)

_Seria legal se ao passar o mouse em cima do nome ele mostrasse um tooltip com o nome inteiro mas não vi uma maneira de fazer isso pela lib._

**Comment by luizbaldi** [comment]
Show demais @brunodesde1987, muito obrigado pela issue! Você tem interesse em abrir um PR com a resolução desse problema? haha

**Comment by brunodesde1987** [comment]
Eu tinha tentado abrir e ocorreu algum erro de permissão, mas tenho interesse sim rs 👍
