### ISSUE TITLE
Playlist Converter Demo

### ISSUE THREAD

**Issue by mikeyoyetunde** [luizbaldi/playlist-converter#11]
Hi Luiz,

I was trying to log in via spotify using your playlist converter demo. But I kept getting an error can you please check it out

**Comment by luizbaldi** [comment]
Hi @mikeyoyetunde,

Thanks for getting in touch and notifying me about this, the problem was fixed. Could you try logging in again?

Besides, feel free to make suggestions on how to improve the app if you see some areas for improvement 😄

**Comment by luizbaldi** [comment]
@mikeyoyetunde Closing this issue because looks like it was solved, in case you're still having problems let me know!
