### ISSUE TITLE
Pequeno bug ao tentar converter uma playlist sem selecioná-la manualmente

### ISSUE THREAD

**Issue by brunodesde1987** [luizbaldi/playlist-converter#2]
👀 

### Problema
Erro acontece no seguinte cenário:
1) Me conectei em ambas plataformas
2) Quero converter a primeira playlist que aparece para mim no `Select` do Spotify
3) Como ele não passa pelo `onChange`, ele entende que não existe uma playlist selecionada e retorna erro

Obs: Existe um erro de digitação na mensagem que aparece. Ao invés de _origin_ está _origni_.

![error-current-playlist](https://user-images.githubusercontent.com/28319535/78160018-bd783e80-7419-11ea-938d-c4bdd64fd4a3.gif)

### Sugestão
Talvez um `useEffect` para observar `playlists.items` e usar o `setCurrentPlaylist` para o primeiro item da lista. 
Sinceramente não sei se é a melhor opção, foi o que consegui pensar no momento rs 🤷‍♂

**Comment by luizbaldi** [comment]
Novamente obrigado pela issue @brunodesde1987! Acredito que isso seja um comportamento do componente de Select do react95 mesmo, vou dar uma olhada :) (caso voce tenha interesse em resolver isso também é só avisar 😄)
